### ISSUE TITLE
Entering a command fails on a FXOS TV

### ISSUE THREAD

**Issue by sylvestre** [potch/corsica-repl#2]
We tried to use corsica-repl on a fxos but we cannot enter an command. We can type the command (repl server http://corsica.mozilla.io/ but pressing Enter has no effect)

**Comment by miketaylr** [comment]
The process should be something like this:

On the Firefox OS TV, navigate to corsica.mozilla.io. Watch what name it gives itself when it connects (you'll see a little "toast" message).

From another computer, load the corsica-repl. You can use the hosted instance if you don't want to set that upyourself: http://potch.github.io/corsica-repl/

From the remote repl, pick the name of your TV and type the commands in.

**Comment by sylvestre** [comment]
Oh, this is great, with your doc, I have been able to run it. No need to enter anything on the TV! Thanks
I will write a PR to explain all this more into details! Thanks!

**Comment by miketaylr** [comment]
:cake: :balloon:
